LineColorMenu
QActionGroup* LineColorMenu::d_grp
QList<QAction *> LineColorMenu::d_act
int LineColorMenu::d_which
LineColorMenu::LineColorMenu(int which, QWidget *parent)
References getBlack, getBlue, getCyan, getDarkBlue, getDarkGray, getDarkGreen, getDarkRed, getGray, getGreen, getMagenta, getRed, getYellow.
LineColorMenu::~LineColorMenu()
int LineColorMenu::getNumActions() const
QAction* LineColorMenu::getAction(int which)
References whichTrigger.
void LineColorMenu::whichTrigger(int which, const QString &name)
Referenced by AverageMenu::AverageMenu, FFTSizeMenu::FFTSizeMenu, FFTSizeMenu::get05, FFTSizeMenu::get06, FFTSizeMenu::get07, FFTSizeMenu::get08, FFTSizeMenu::get09, FFTSizeMenu::get10, FFTSizeMenu::get11, FFTSizeMenu::get12, getAction, LineWidthMenu::getAction, LineStyleMenu::getAction, LineMarkerMenu::getAction, MarkerAlphaMenu::getAction, ColorMapMenu::getAction, TriggerModeMenu::getAction, TriggerSlopeMenu::getAction, TriggerChannelMenu::getAction, NumberLayoutMenu::getAction, NumberColorMapMenu::getAction, FFTSizeMenu::getActionFromSize, FFTWindowMenu::getActionFromWindow, TriggerModeMenu::getAuto, getBlack, NumberColorMapMenu::getBlack, ColorMapMenu::getBlackHot, NumberColorMapMenu::getBlackHot, FFTWindowMenu::getBlackman, FFTWindowMenu::getBlackmanharris, NumberColorMapMenu::getBlackRed, getBlue, NumberColorMapMenu::getBlueRed, TriggerChannelMenu::getChannel, LineMarkerMenu::getCircle, ColorMapMenu::getCool, LineMarkerMenu::getCross, getCyan, getDarkBlue, getDarkGray, getDarkGreen, getDarkRed, LineStyleMenu::getDash, LineStyleMenu::getDashDot, LineStyleMenu::getDashDotDot, LineMarkerMenu::getDiamond, LineStyleMenu::getDots, LineMarkerMenu::getDTriangle, LineWidthMenu::getEight, LineWidthMenu::getFive, FFTWindowMenu::getFlattop, LineWidthMenu::getFour, TriggerModeMenu::getFree, getGray, getGreen, FFTWindowMenu::getHamming, FFTWindowMenu::getHann, LineMarkerMenu::getHexagon, MarkerAlphaMenu::getHigh, AverageMenu::getHigh, LineMarkerMenu::getHLine, NumberLayoutMenu::getHoriz, ColorMapMenu::getIncandescent, FFTWindowMenu::getKaiser, MarkerAlphaMenu::getLow, AverageMenu::getLow, LineMarkerMenu::getLTriangle, getMagenta, MarkerAlphaMenu::getMedium, AverageMenu::getMedium, ColorMapMenu::getMultiColor, TriggerSlopeMenu::getNeg, LineWidthMenu::getNine, LineStyleMenu::getNone, LineMarkerMenu::getNone, MarkerAlphaMenu::getNone, FFTWindowMenu::getNone, NumberLayoutMenu::getNone, TriggerModeMenu::getNorm, MarkerAlphaMenu::getOff, AverageMenu::getOff, LineWidthMenu::getOne, FFTSizeMenu::getOther, AverageMenu::getOther, ColorMapMenu::getOther, NumberColorMapMenu::getOther, TriggerSlopeMenu::getPos, LineMarkerMenu::getRect, FFTWindowMenu::getRectangular, getRed, LineMarkerMenu::getRTriangle, LineWidthMenu::getSeven, LineWidthMenu::getSix, LineStyleMenu::getSolid, LineMarkerMenu::getStar1, LineMarkerMenu::getStar2, ColorMapMenu::getSunset, TriggerModeMenu::getTag, LineWidthMenu::getTen, LineTitleAction::getTextDiag, OtherAction::getTextDiag, OtherDualAction::getTextDiag, NPointsMenu::getTextDiag, PopupMenu::getTextDiag, ItemFloatAct::getTextDiag, LineWidthMenu::getThree, LineMarkerMenu::getTriangle, LineWidthMenu::getTwo, NumberLayoutMenu::getVert, LineMarkerMenu::getVLine, ColorMapMenu::getWhiteHot, NumberColorMapMenu::getWhiteHot, LineMarkerMenu::getXCross, getYellow, OtherAction::setDiagText, AverageMenu::setLow, PopupMenu::setText, ItemFloatAct::setText, LineTitleAction::~LineTitleAction, NPointsMenu::~NPointsMenu, OtherDualAction::~OtherDualAction.
void LineColorMenu::getBlue()
References whichTrigger.
Referenced by LineColorMenu.
void LineColorMenu::getRed()
References whichTrigger.
Referenced by LineColorMenu.
void LineColorMenu::getGreen()
References whichTrigger.
Referenced by LineColorMenu.
void LineColorMenu::getBlack()
References whichTrigger.
Referenced by LineColorMenu, NumberColorMapMenu::NumberColorMapMenu.
void LineColorMenu::getCyan()
References whichTrigger.
Referenced by LineColorMenu.
void LineColorMenu::getMagenta()
References whichTrigger.
Referenced by LineColorMenu.
void LineColorMenu::getYellow()
References whichTrigger.
Referenced by LineColorMenu.
void LineColorMenu::getGray()
References whichTrigger.
Referenced by LineColorMenu.
void LineColorMenu::getDarkRed()
References whichTrigger.
Referenced by LineColorMenu.
void LineColorMenu::getDarkGreen()
References whichTrigger.
Referenced by LineColorMenu.
void LineColorMenu::getDarkBlue()
References whichTrigger.
Referenced by LineColorMenu.
void LineColorMenu::getDarkGray()
References whichTrigger.
Referenced by LineColorMenu.