LiveDemo:
	#rm ~/prefix/gr-ieee802-11/build/randomtest1.txt
	sudo python ~/prefix/gr-ieee802-11/examples/wifi_rx.py
	#sudo gr_read_file_metadata ~/prefix/gr-ieee802-11/build/metadata > ~/prefix/gr-ieee802-11/build/randomtest1.txt 
	#python ./build/extractData_Live.py
